import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Clock3 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../api/client';
import { AsyncPanel } from '../components/AsyncPanel';
import { PriceTrend } from '../components/Charts';
import { MetricCard } from '../components/MetricCard';
import { PageHeader } from '../components/PageHeader';
import { RiskBadge } from '../components/RiskBadge';
import { money, pct } from '../lib/domain';
export function Overview(){const q=useQuery({queryKey:['overview'],queryFn:api.overview});return <><PageHeader eyebrow="Market pulse" title="Good morning, procurement team" description="A decision-focused view of current food price movement and volatility." action={<Link className="button primary" to="/forecast">Create forecast <ArrowRight/></Link>}/><AsyncPanel loading={q.isLoading} error={q.error} onRetry={()=>q.refetch()}>{q.data&&<><section className="metrics">{q.data.kpis.map(k=><MetricCard key={k.label}{...k}/>)}</section><section className="dashboard-grid"><article className="panel wide"><div className="panel-head"><div><span className="overline">12-month movement</span><h2>Red Nadu wholesale price</h2></div><div className="legend"><span className="primary-line">Market</span><span className="secondary-line">Regional avg.</span></div></div><PriceTrend data={q.data.trend}/></article><article className="panel"><div className="panel-head"><div><span className="overline">Volatility watch</span><h2>Items requiring attention</h2></div><Link to="/market-explorer">Explore all</Link></div><div className="risk-list">{q.data.risks.slice(0,3).map(r=><div key={r.commodity}><div><strong>{r.commodity}</strong><span>{r.market}</span></div><div className="risk-value"><strong>{money(r.price)}</strong><span className={r.change<0?'down':'up'}>{pct(r.change)}</span></div><RiskBadge level={r.risk}/></div>)}</div></article></section><section className="panel table-panel"><div className="panel-head"><div><span className="overline">Cross-market signals</span><h2>Latest observed prices</h2></div><span className="updated"><Clock3/>Updated 20 Sep, 18:30</span></div><div className="table-wrap"><table><thead><tr><th>Commodity</th><th>Market</th><th>Latest price</th><th>Change</th><th>Volatility</th><th></th></tr></thead><tbody>{q.data.risks.map(r=><tr key={r.commodity}><td><strong>{r.commodity}</strong></td><td>{r.market}</td><td>{money(r.price)}/kg</td><td className={r.change<0?'down':'up'}>{pct(r.change)}</td><td><RiskBadge level={r.risk}/></td><td><Link aria-label={`Forecast ${r.commodity}`} to={`/forecast?commodity=${encodeURIComponent(r.commodity)}`}><ArrowRight/></Link></td></tr>)}</tbody></table></div></section></>}</AsyncPanel></>}
